-- Session #1
-- postgres=# BEGIN;
-- BEGIN
-- postgres=*# SHOW TRANSACTION ISOLATION LEVEL;
--  transaction_isolation
-- -----------------------
--  read committed
-- (1 row)
--
-- postgres=*# SELECT SUM(rating) FROM pizzeria;
--  sum
-- ------
--  21.9
-- (1 row)
--
-- postgres=*# SELECT SUM(rating) FROM pizzeria;
--  sum
-- ------
--  19.9
-- (1 row)
--
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT SUM(rating) FROM pizzeria;
--  sum
-- ------
--  19.9
-- (1 row)
--
-- postgres=#
-- -------------------------------------------------------------------
-- Session #2
-- postgres=# BEGIN;
-- BEGIN
-- postgres=*# SHOW TRANSACTION ISOLATION LEVEL;
--  transaction_isolation
-- -----------------------
--  read committed
-- (1 row)
--
-- postgres=*# SELECT SUM(rating) FROM pizzeria;
--  sum
-- ------
--  21.9
-- (1 row)
--
-- postgres=*# UPDATE pizzeria SET rating = 1 WHERE name = 'Pizza Hut';
-- UPDATE 1
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT SUM(rating) FROM pizzeria;
--  sum
-- ------
--  19.9
-- (1 row)
--
-- postgres=#
