-- Session #1
-- postgres=# BEGIN;
-- BEGIN
-- postgres=*# SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET
-- postgres=*# SHOW TRANSACTION ISOLATION LEVEL;
--  transaction_isolation
-- -----------------------
--  serializable
-- (1 row)
--
-- postgres=*# SELECT * FROM pizzeria WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
--
-- postgres=*# SELECT * FROM pizzeria WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
--
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT * FROM pizzeria WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.0
-- (1 row)
--
-- postgres=#
-- -----------------------------------------------------------------
-- Session #2
-- postgres=# BEGIN;
-- BEGIN
-- postgres=*# SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- SET
-- postgres=*# SHOW TRANSACTION ISOLATION LEVEL;
--  transaction_isolation
-- -----------------------
--  serializable
-- (1 row)
--
-- postgres=*# SELECT * FROM pizzeria WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
--
-- postgres=*# UPDATE pizzeria SET rating = 3.0 WHERE name = 'Pizza Hut';
-- UPDATE 1
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT * FROM pizzeria WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.0
-- (1 row)
--
-- postgres=#
